# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0003_paymenttype_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vattype',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
