# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0006_auto_20171023_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.FileField(default=None, upload_to='invoices'),
        ),
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(default=None, upload_to='orders'),
        ),
    ]
