# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0007_auto_20171023_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC.Provider'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC.VatType'),
        ),
    ]
