# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0008_auto_20171103_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
