# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0009_auto_20171103_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
