# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0010_auto_20171221_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
