# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0013_auto_20171221_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
