# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0016_auto_20180119_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_code',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='web',
            field=models.URLField(blank=True, default='http://'),
        ),
    ]
