# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0017_auto_20180119_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cif',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
