# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0018_auto_20180119_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cif',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
