# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0020_auto_20180119_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
