# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0022_auto_20180120_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 150577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='notice_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 150694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 152787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 152811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 151180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 151207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 154423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 154466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='notice_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 154631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 17, 24, 154446, tzinfo=utc)),
        ),
    ]
