# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0023_auto_20180121_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 961288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='notice_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 961411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 963475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 963499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 961899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 961927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 965102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 965143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='notice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 13, 18, 2, 965124, tzinfo=utc)),
        ),
    ]
