# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0028_auto_20180121_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ABC.Customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ABC.Provider'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='notice',
            field=models.TextField(default=''),
        ),
    ]
