# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0033_auto_20180125_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='cost_currency',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
