# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0035_auto_20180126_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vattype',
            name='rate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
