# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0036_auto_20180126_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ABC.DeliveryType'),
        ),
    ]
