# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0037_auto_20180131_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
