# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0038_auto_20180131_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
