# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0040_auto_20180207_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('TD', 'To do'), ('DNG', 'Doing'), ('DN', 'Done'), ('DIS', 'Discarded')], default='To do', max_length=50),
        ),
    ]
