# Generated by Django 2.0.3 on 2018-07-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0042_auto_20180607_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
