# Generated by Django 2.0.3 on 2018-07-03 15:16

import ABC.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0043_remove_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[(ABC.models.States('Ordered'), 'Ordered'), (ABC.models.States('Not Ready'), 'Not Ready'), (ABC.models.States('Ready'), 'Ready'), (ABC.models.States('Sent'), 'Sent'), (ABC.models.States('Paid'), 'Paid')], default=ABC.models.States('Not Ready'), max_length=5),
        ),
    ]
