# Generated by Django 2.0.3 on 2018-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC', '0044_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('O', 'Ordered'), ('NR', 'Not Ready'), ('R', 'Ready'), ('S', 'Sent'), ('P', 'Paid')], default='Ordered', max_length=50),
        ),
    ]
